=begin
#Voucherify API

#Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

The version of the OpenAPI document: v2018-08-01
Contact: support@voucherify.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module VoucherifySdk
  class ExportPublicationOrder
    VOUCHER_CODE = "voucher_code".freeze
    VOUCHER_CODE2 = "-voucher_code".freeze
    CUSTOMER_ID = "customer_id".freeze
    CUSTOMER_ID2 = "-customer_id".freeze
    CUSTOMER_SOURCE_ID = "customer_source_id".freeze
    CUSTOMER_SOURCE_ID2 = "-customer_source_id".freeze
    DATE = "date".freeze
    DATE2 = "-date".freeze
    CHANNEL = "channel".freeze
    CHANNEL2 = "-channel".freeze
    CAMPAIGN = "campaign".freeze
    CAMPAIGN2 = "-campaign".freeze
    IS_WINNER = "is_winner".freeze
    IS_WINNER2 = "-is_winner".freeze
    METADATA = "metadata".freeze
    METADATA2 = "-metadata".freeze

    def self.all_vars
      @all_vars ||= [VOUCHER_CODE, VOUCHER_CODE2, CUSTOMER_ID, CUSTOMER_ID2, CUSTOMER_SOURCE_ID, CUSTOMER_SOURCE_ID2, DATE, DATE2, CHANNEL, CHANNEL2, CAMPAIGN, CAMPAIGN2, IS_WINNER, IS_WINNER2, METADATA, METADATA2].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ExportPublicationOrder.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ExportPublicationOrder"
    end
  end
end
