=begin
#Voucherify API

#Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

The version of the OpenAPI document: v2018-08-01
Contact: support@voucherify.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module VoucherifySdk
  class ExportPointsExpirationOrder
    ID = "id".freeze
    ID2 = "-id".freeze
    CAMPAIGN_ID = "campaign_id".freeze
    CAMPAIGN_ID2 = "-campaign_id".freeze
    VOUCHER_ID = "voucher_id".freeze
    VOUCHER_ID2 = "-voucher_id".freeze
    POINTS = "points".freeze
    POINTS2 = "-points".freeze
    STATUS = "status".freeze
    STATUS2 = "-status".freeze
    EXPIRES_AT = "expires_at".freeze
    EXPIRES_AT2 = "-expires_at".freeze

    def self.all_vars
      @all_vars ||= [ID, ID2, CAMPAIGN_ID, CAMPAIGN_ID2, VOUCHER_ID, VOUCHER_ID2, POINTS, POINTS2, STATUS, STATUS2, EXPIRES_AT, EXPIRES_AT2].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ExportPointsExpirationOrder.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ExportPointsExpirationOrder"
    end
  end
end
